1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [34]:
import numpy as np
import pandas as pd
from scipy import stats

In [16]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

mzp = zp.mean()
mks = ks.mean()

cov = ((zp - mzp) * (ks - mks)).sum() / (zp.shape[0] - 1)
cov

10175.37777777778

In [17]:
cov = np.cov(zp, ks, ddof=1)
cov

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [18]:
corr = cov / (zp.std() * ks.std())
corr

array([[0.37629669, 0.9861001 ],
       [0.9861001 , 3.28083648]])

In [19]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [23]:
zp_p = pd.Series([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks_p = pd.Series([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
pd_dataframe = pd.DataFrame({'zp_p': zp_p, 'ks_p': ks_p})
pd_dataframe.corr(method='pearson')

zp_p     ks_p
zp_p  1.00000  0.88749
ks_p  0.88749  1.00000

Question: не понимаю почему numpy и pandas, и ручной расчет возвращают разные значения. Подумал, что может быть разница в cov, но замена параметра не помогла

2. Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [24]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])

In [32]:
s_mean = iq.mean()
n = iq.shape[0]
se = stats.sem(iq)
confidence = 0.95
h = se * stats.t.ppf((1 + confidence) / 2., n-1)
s_mean-h, s_mean+h

(110.55608365158724, 125.64391634841274)

3. Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

In [35]:
s_mean = 174.2
n = 27
sd = 25
se = sd / np.sqrt(n)
confidence = 0.95
h = se * stats.t.ppf((1 + confidence) / 2., n-1)
s_mean-h, s_mean+h

(164.31032937726948, 184.0896706227305)

4. Выберите тему для проектной работы по курсу Теории вероятностей и математической статистики
и напишите ее в комментарии к Практическому заданию.

Не до конца понял задание, но для моей работы будет полезна тема "Метод главных компонент. Логистическая регрессия"
Что нужно далее делать?